version: "3"
# x-awc-vpc: "vpc-id-string "
services:
  # nginx:
  #   restart: always
  #   image: "marcosjampietri/nginx:latest"
  #   ports:
  #     - "5150:80"
  # api:
  #   image: "marcosjampietri/api:latest"
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app
  #   links:
  #     - mongo
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     DATABASE: "$DATABASE"
  #     PORT: "$PORT"
  # mongo:
  #   image: "mongo"
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
  nextjs:
    image: "marcosjampietri/three-docker-repo:latest"
    # links:
    #   - mongo
    ports:
      - "3000:3000"
