version: "3"
# x-awc-vpc: "vpc-id-string "
services:
  nginx:
    restart: always
    image: "marcosjampietri/nginx:0.1"
    ports:
      - "5150:80"
  api:
    image: "marcosjampietri/api:0.1"
    links:
      - mongo
    ports:
      - "5000:5000"
    environment:
      DATABASE: "$DATABASE"
      PORT: "$PORT"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
  nextjs:
    image: "marcosjampietri/three-docker-repo:0.1"
    links:
      - mongo
    ports:
      - "3000:3000"
